### ISSUE TITLE
links

### ISSUE THREAD

**Issue by joshinils** [philsupertramp/wiki#11]
sollten nicht ein benanntes template sein, sondern eine eigene syntax besitzen wie
 * `[[seitenname]]` -> `url.de/wiki/seitenname/`
 * `[[seitenname/foo]]` -> `url.de/wiki/seitenname/foo`
 * `[[user:name]]` -> `url.de/user/name/`

einrichten von weiterleitungen, diese werden dann angezeigt bei der seite wo man landet, damit man das merkt (zb. als "weitergeletet von: xy", dann rest der eigentlichen ziel-seite)

**Comment by joshinils** [comment]
wirklich nicht was das Problem mit
``` md
# Title1
# Title2
[https://www.markdownguide.org/](Hier) solltest du unbedingt mal draufklicken!
[/auch-hier](Auch das) geht lokal.
Ich kann sogar im Dokument [#Title1](verlinken)
```
ist.

**Comment by joshinils** [comment]
naja, da gebe ich dann ja explizit die links an. der vorteil dieser anderen syntax wäre, dass ich mich nicht um den namen des links kümmern muss, also mit welchem text der hinterher erscheint (das kann dann ja auf der seite wo das hin linkt definiert sein).

außerdem schließt das die markdown style links ja nicht aus, das geht dann ja auch extern (ist das dann erkennbar durch css einfärbung?).

ich bin das so gewöhnt, begründen kann ich das jetzt auch nicht sonderlich gut

**Comment by philsupertramp** [comment]
Seiten können mit 

- `[test page](https://wiki.godesteem.de/wiki/test123/)`
- `[name](/wiki/subpage)`
- `[[ wiki:foobar ]]`

angesprochen werden

**Comment by philsupertramp** [comment]
tote links verweisen auf momentane seite
